[project]
name = "agentic-ppt"
version = "1.0.0"
description = "AI-powered PDF to PowerPoint presentation generator"
readme = "README.md"
requires-python = ">=3.8"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
] 